apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlconfigmap
data:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: database
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  create_table.sql: |
    CREATE TABLE IF NOT EXISTS form_data (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL,
        message TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );