apiVersion: v1
kind: Service
metadata:
  name: php-webserver
  namespace: webapp-namespace
spec:
  selector:
    app: php-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort